### ISSUE TITLE
Nanopb 0.3.9-dev seems to hang the firmware

### ISSUE THREAD

**Issue by precision** [google/science-journal-arduino#22]
While testing with Merlin it appears that the latest Nanopb library causes the firmware to hang.

**Comment by dakoner** [comment]
Does an older version of nanopb work?

**Comment by precision** [comment]
Yes 0.3.8-dev works fine.  I commited a fix to the platformio.ini to force 0.3.8-dev until we can determine what in 0.3.9 breaks things.

**Comment by eric-wieser** [comment]
([relevant lines here](https://github.com/google/science-journal-arduino/blob/master/platformio.ini#L29))

This is going to stop working, as `0.3.8-dev` has been removed from the package manager (https://github.com/nanopb/nanopb/commit/cc74b9f200176edc5524aa00ba45fa90a5e87d27#commitcomment-23061529)

**Comment by ivankravets** [comment]
Sorry for the issue, the `0.3.8-dev` version has been just restored. In any case, I recommend to depend on `0.3.7` which is the same as `0.3.8-dev`.

See http://platformio.org/lib/show/431/Nanopb

**Comment by eric-wieser** [comment]
That issue is probably why `0.3.9-dev` didn't work for you in the first place. You might now find that `0.3.8` works properly, now that that platformio package and protoc plugin versions are in sync

**Comment by precision** [comment]
Thanks for the info.  I'll pin @0.3.7.  @0.3.8 is still giving me errors on installation here.
