### ISSUE TITLE
Please make the code compatible with the Arduino IDE

### ISSUE THREAD

**Issue by mbanzi** [google/science-journal-arduino#25]
Right now this code is not useable on the Arduino IDE which has several million users.. 
It would make it simpler for many people to contribute and port to other hardware.

**Comment by lemio** [comment]
Here is the pre-compiled firmware for the 101 board, if that helps anyone...
[101.zip](https://github.com/google/science-journal-arduino/files/2356199/101.zip)

**Comment by precision** [comment]
Arduino IDE compat tree is @ https://github.com/google/science-journal-arduino/tree/arduino-ide
