### ISSUE TITLE
Unable to compile Obstacle avoidance Sketch to Arduino.

### ISSUE THREAD

**Issue by JITESHNAIR01** [google/science-journal-arduino#28]
Arduino: 1.8.6 (Windows Store 1.8.14.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\JP\Desktop\aiyprojects\obstacle_avoiding_robot\obstacle_avoiding_robot.ino: In function 'void loop()':

obstacle_avoiding_robot:45:25: error: 'class Ultrasonic' has no member named 'Ranging'

    front_d = ultrasonic.Ranging(CM); // measuring fornt distance  

                         ^

obstacle_avoiding_robot:45:33: error: 'CM' was not declared in this scope

    front_d = ultrasonic.Ranging(CM); // measuring fornt distance  

                                 ^

C:\Users\JP\Desktop\aiyprojects\obstacle_avoiding_robot\obstacle_avoiding_robot.ino: In function 'void get_d()':

obstacle_avoiding_robot:108:26: error: 'class Ultrasonic' has no member named 'Ranging'

     right_d = ultrasonic.Ranging(CM);     

                          ^

obstacle_avoiding_robot:108:34: error: 'CM' was not declared in this scope

     right_d = ultrasonic.Ranging(CM);     

                                  ^

obstacle_avoiding_robot:111:26: error: 'class Ultrasonic' has no member named 'Ranging'

     front_d = ultrasonic.Ranging(CM);     

                          ^

obstacle_avoiding_robot:114:25: error: 'class Ultrasonic' has no member named 'Ranging'

     left_d = ultrasonic.Ranging(CM);  

                         ^

exit status 1
'class Ultrasonic' has no member named 'Ranging'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by JITESHNAIR01** [comment]
please review and let me know how to fix the issue

**Comment by precision** [comment]
I don't think this was meant for this repository? Maybe https://github.com/google/aiyprojects-raspbian?
